"""Canonical research lifecycle states."""
from enum import Enum


class ResearchState(str, Enum):
    IDEA = "IDEA"
    QUESTION_DEFINED = "QUESTION_DEFINED"
    FRAMEWORK_DEFINED = "FRAMEWORK_DEFINED"
    DESIGN_SELECTED = "DESIGN_SELECTED"
    PROTOCOL_READY = "PROTOCOL_READY"
    LITERATURE_SEARCH = "LITERATURE_SEARCH"
    SCREENING = "SCREENING"
    DATA_COLLECTION = "DATA_COLLECTION"
    DATA_READY = "DATA_READY"
    ANALYSIS_PLAN_LOCKED = "ANALYSIS_PLAN_LOCKED"
    ANALYSIS_COMPLETE = "ANALYSIS_COMPLETE"
    MANUSCRIPT_DRAFT = "MANUSCRIPT_DRAFT"
    AUDIT = "AUDIT"
    JOURNAL_SELECTION = "JOURNAL_SELECTION"
    READY_FOR_SUBMISSION = "READY_FOR_SUBMISSION"
